name: kassakuitti
description: A starting point for Dart libraries or applications.
version: 0.1.0
# homepage: https://www.example.com

publish_to: 'none' # for now, do not publish the package into pub.dev

environment:
  sdk: '>=2.18.2 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
