name: kassakuitti
description: A Dart package for handling "dart_kassakuitti_cli" & "rvka" Flutter GUI 
version: 0.1.0
homepage: https://github.com/areee/kassakuitti

publish_to: 'none' # for now, do not publish the package into pub.dev

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  excel: ^2.0.0-null-safety-3
  html: ^0.15.1
  intl: ^0.17.0
  path: ^1.8.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
