name: kassakuitti
description: A Dart package for handling a cash receipt coming from S-kaupat or K-ruoka (two Finnish food online stores).
version: 0.8.0
repository: https://github.com/areee/kassakuitti

environment:
  sdk: ^3.1.2

dependencies:
  flutter_excel: ^1.0.1
  html: ^0.15.4
  intl: ^0.18.1
  mime: ^1.0.4
  path: ^1.8.3

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.6
