name: kassakuitti
description: A Dart package for handling a cash receipt coming from S-kaupat or K-ruoka (two Finnish food online stores).
version: 0.7.0
repository: https://github.com/areee/kassakuitti

environment:
  sdk: ^3.0.0

dependencies:
  flutter_excel: ^1.0.1
  html: ^0.15.3
  intl: ^0.18.1
  mime: ^1.0.4
  path: ^1.8.3
  tuple: ^2.0.1

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.2
